[tool.poetry]
name = "necst-lib"
version = "0.1.0"
description = "Pure Python tools for NECST."
license = "MIT"
readme = "README.md"
authors = ["KaoruNishikawa <k.nishikawa@a.phys.nagoya-u.ac.jp>"]
homepage = "https://github.com/nanten2/necst-lib"
repository = "https://github.com/nanten2/necst-lib"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19"

[tool.poetry.dev-dependencies]
black = "^21.10b"
flake8 = "^3.8"
ipykernel = "^6.3"
m2r2 = "^0.2"
pydata-sphinx-theme = "^0.4"
pytest = "^5.2"
sphinx = "^3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
